DROP TABLE Branch CASCADE CONSTRAINTS;
DROP TABLE Volunteer CASCADE CONSTRAINTS;
DROP TABLE Donor CASCADE CONSTRAINTS;
DROP TABLE Campaign CASCADE CONSTRAINTS;
DROP TABLE Employee CASCADE CONSTRAINTS;
DROP TABLE Activity CASCADE CONSTRAINTS;
DROP TABLE WorksOn CASCADE CONSTRAINTS;
DROP TABLE Manages CASCADE CONSTRAINTS;
DROP TABLE DonatesFor CASCADE CONSTRAINTS;
DROP TABLE BranchPhones CASCADE CONSTRAINTS;

CREATE TABLE Branch
(BID NUMBER(3) PRIMARY KEY,
Address VARCHAR2(50) NOT NULL);

CREATE TABLE Volunteer 
(FNAME VARCHAR2(10) NOT NULL, 
LNAME VARCHAR2(10) NOT NULL, 
EMAIL VARCHAR2(20) PRIMARY KEY, 
BIRTHDATE DATE NOT NULL,
MOBILENUMBER VARCHAR2(13) NOT NULL, 
ADDRESS VARCHAR2(50));

CREATE TABLE Donor 
(FNAME VARCHAR2(10) NOT NULL, 
LNAME VARCHAR2(10) NOT NULL, 
EMAIL VARCHAR2(20) PRIMARY KEY, 
MOBILENUMBER VARCHAR2(13) NOT NULL, 
ADDRESS VARCHAR2(50));

CREATE TABLE Campaign
(CampName VARCHAR2(30),
CampDate DATE,
CampLocation VARCHAR2(50) NOT NULL,
NumOfReqVolunteer NUMBER(7) NOT NULL,
CONSTRAINTS pkCampaign PRIMARY KEY(CampName, CampDate));
                               
CREATE TABLE Employee
(SSN NUMBER(15) PRIMARY KEY, 
FNAME VARCHAR2(10) NOT NULL, 
LNAME VARCHAR2(10) NOT NULL, 
EMAIL VARCHAR2(20), 
MOBILENUMBER VARCHAR2(13) NOT NULL, 
ADDRESS VARCHAR2(50),
BID NUMBER(3) REFERENCES Branch(BID));

CREATE TABLE Activity
(ActName VARCHAR2(30) NOT NULL,
CampName VARCHAR2(30),
CampDate DATE,
CONSTRAINTS pkActivity PRIMARY KEY(ActName, CampName, CampDate),
CONSTRAINTS fkActivity FOREIGN KEY(CampName, CampDate) REFERENCES Campaign(CampName, CampDate));

CREATE TABLE WorksOn
(VolunteerEmail VARCHAR2(20) REFERENCES Volunteer(Email),
CampName VARCHAR2(30),
CampDate DATE,
CONSTRAINTS pkWorksOn PRIMARY KEY(VolunteerEmail, CampName, CampDate),
CONSTRAINTS fkWorksOn FOREIGN KEY(CampName, CampDate) REFERENCES Campaign(CampName, CampDate));

CREATE TABLE Manages
(BID NUMBER(3) REFERENCES Branch(BID),
CampName VARCHAR2(30),
CampDate DATE,
CONSTRAINTS pkManages PRIMARY KEY(BID, CampName, CampDate),
CONSTRAINTS fkManages FOREIGN KEY(CampName, CampDate) REFERENCES Campaign(CampName, CampDate));

CREATE TABLE DonatesFor
(DonorEmail VARCHAR2(20) REFERENCES Donor(Email),
CampName VARCHAR2(30),
CampDate DATE,
ReceiptNumber NUMBER(10) NOT NULL,
DonationDate Date NOT NULL,
DonationType VARCHAR2(20) NOT NULL,
Amount NUMBER(10) NOT NULL,
CONSTRAINTS pkDonatesFor PRIMARY KEY(DonorEmail, CampName, CampDate),
CONSTRAINTS fkDonatesFor FOREIGN KEY(CampName, CampDate) REFERENCES Campaign(CampName, CampDate));
   
CREATE TABLE BranchPhones
(BID NUMBER(3) REFERENCES Branch(BID),
MOBILENUMBER VARCHAR2(13) NOT NULL, 
CONSTRAINTS pkBranchPhones PRIMARY KEY (BID, MOBILENUMBER));
